# Generated by Django 4.0 on 2021-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_project_blog_image_remove_project_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project_blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
