# Generated by Django 4.0 on 2021-12-12 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_project_blog_description_project_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 22, 38, 41, 691887)),
        ),
    ]
