# Generated by Django 4.0 on 2021-12-12 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_project_blog_description_alter_project_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='default')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 1, 7, 455780))),
            ],
        ),
        migrations.DeleteModel(
            name='Project_blog',
        ),
    ]
