# Generated by Django 4.1 on 2022-08-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
